steps:
  - command: "npm ci && npm run build && npm version major  --no-git-tag-version  && git push origin HEAD:master && copy package*.json build && cd build && npm pack"
    artifact_paths:
    - "build/movie-raja*.tgz" 