steps:
  - command: "npm ci && npm run build && npm version major  --no-git-tag-version && git add . && git commit -m \"new build\" && git push origin && copy package*.json build && cd build && npm pack"
    artifact_paths:
    - "build/movie-raja*.tgz" 